// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.731
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Homepage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<html><head><title>WS testing</title><script src=\"https://unpkg.com/htmx.org@2.0.0\"></script><script src=\"https://unpkg.com/htmx-ext-ws@2.0.0/ws.js\"></script></head><body><div hx-ext=\"ws\" ws-connect=\"/ws/submit\"><h2>ws testing</h2><div><form ws-send><input type=\"text\" name=\"name\" value=\"single array item\"> <input type=\"text\" name=\"items[]\" value=\"a\"> <button type=\"submit\">submit</button></form></div><div><form ws-send><input type=\"text\" name=\"name\" value=\"multiple array item\"> <input type=\"text\" name=\"items[]\" value=\"a\"> <input type=\"text\" name=\"items[]\" value=\"b\"> <button type=\"submit\">submit</button></form></div></div><div><h2>form testing</h2><div><form method=\"post\" action=\"/submit\"><input type=\"text\" name=\"name\" value=\"single array item\"> <input type=\"text\" name=\"items[]\" value=\"a\"> <button type=\"submit\">submit</button></form></div><div><form method=\"post\" action=\"/submit\"><input type=\"text\" name=\"name\" value=\"multiple array item\"> <input type=\"text\" name=\"items[]\" value=\"a\"> <input type=\"text\" name=\"items[]\" value=\"b\"> <button type=\"submit\">submit</button></form></div></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
